name: Python CI

on:
  push: 
    branches:
    - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}


  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest main_test.py

    
    - name: Run Tests and Capture Output
      run: |
        pytest main_test.py >> test_results.log  # Capture output in test_results.log

    - name: Upload Test Results (optional)
      uses: actions/upload-artifact@v3
      with:
        name: test_results
        path: test_results.log